name = "aiken-extra/string_util"
version = "2.160.202309"
license = "Apache-2.0"
description = "An Aiken utility library to pretty-print data"

[repository]
user = "aiken-extra"
project = "string_util"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
